[package]
name = "space_colony_sim"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.29.0"
serde = { version = "1.0.213", features = ["derive"] }
serde_json = "1.0.132"
tokio = { version = "1.41.0", features = ["full"] }
toml = "0.8.19"
